# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-117.0382, 32.5149, srid=4326), srid=4326)),
                ('address', models.CharField(blank=True, max_length=254)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(default='Tijuana', max_length=100)),
                ('state', models.CharField(default='BN', max_length=3)),
                ('country', models.CharField(default='MX', max_length=2)),
                ('public', models.BooleanField(default=True)),
                ('zipcode', models.CharField(max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_verified', models.DateField(blank=True, null=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='photos/None/no-img.jpg', upload_to='photos/')),
                ('aed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craed.AED')),
            ],
        ),
    ]
